### PR TITLE
Add test cases for sort commands

### LINKED ISSUE #361: Add test cases for sort commands

### PR DESCRIPTION
**Pull request by LikHern**
Resolve #361

### CODE REVIEW

**Review by Hikoya — COMMENTED** [review]
Looks good but probably want to consider adding negative test cases such as `null` or invalid criterions

**Review by clarence-chew — APPROVED** [review]
LGTM!

**Comment by clarence-chew** [comment]
Leaving this for @Hikoya to check if the suggestion is implemented to merge.

**Review by Hikoya — APPROVED** [review]
LGTM.

**Comment by Hikoya** [comment]
> Leaving this for @Hikoya to check if the suggestion is implemented to merge.

Will be merging as negative test cases has been added for `RSortCommandParserTest` and `SSortCommandParserTest`

**Pull request merged**
