### PR TITLE
Add new ListPanel for food reviews

### LINKED ISSUE #45: Add new ListPanel for food reviews for v1.2
Add a new List panel into the existing user interface.

The end result should look similar to the UI mockup below:

image

### PR DESCRIPTION
**Pull request by Hikoya**
Added a new list panel for food reviews. 

The list is currently duplicated from the sample data and will be replaced with actual food review data in further updates.

The current user interface is as below:

image

Resolve #45

### CODE REVIEW

**Review by clarence-chew — COMMENTED** [review]
Do also handle copyright of images in [copyright.txt](https://github.com/AY2223S1-CS2103-W14-2/tp/blob/master/copyright.txt), otherwise LGTM.

**Comment by Hikoya** [comment]
Reopened PR due to new integration with package name (foodwhere)

**Review by MinHeinA — APPROVED** [review]
Comment made by Clarence on FoodWhere icons copyrights has been addressed. LGTM. Do you want to raise a PR to remove un-used AB3 icons and remove them from copyrigh.txt?

**Comment by Hikoya** [comment]
> Comment made by Clarence on FoodWhere icons copyrights has been addressed. LGTM. Do you want to raise a PR to remove un-used AB3 icons and remove them from copyrigh.txt?

Thank you Min Hein for the comment, as for removing un-used AB3 icons, I will do it in further iterations of the user interface as we continue to refine the product.

I have also resolved the merge conflict caused by changing the application name

**Pull request merged**
