### PR TITLE
Add new user guide URL to Help menu

### LINKED ISSUE #43: Update user guide URL in Help menu for v1.2

### PR DESCRIPTION
**Pull request by Hikoya**
Resolve #43

### CODE REVIEW

**Review by clarence-chew — COMMENTED** [review]
LGTM.

**Comment by Hikoya** [comment]
Reopened PR due to new integration with package name (foodwhere)

**Comment by Hikoya** [comment]
Reopened PR due to new integration with package name (foodwhere)

**Review by clarence-chew — APPROVED** [review]
LGTM.

**Review by MinHeinA — APPROVED** [review]
LGTM

**Pull request merged**
